### ISSUE TITLE
conda env create -f environment.yml problem

### ISSUE THREAD

**Issue by frankjoey2048** [QQQ-yi/DAC#4]
as title, when I try: conda env create -f environment.yml， error occured: 
```bash


$:  conda env create -f environment.yml
2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - conda-forge
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages:
                                                                                                                                               
Preparing transaction: done                                                                                                                    
Verifying transaction: done                                                                                                                    
Executing transaction: done                                                                                                                    
Installing pip dependencies: | Ran pip subprocess with arguments:                                                                              
['/mnt/data5/dock/miniconda3/envs/DAC/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt', '--exists-action=b']                                                                                                                   
Pip subprocess output:                                                                                                                         
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple                                                                                   
Collecting accelerate==0.34.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 1))                                  
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/02/0e/626f2dd4325f4545fbaaf9c590390d2d4ab8e7551579346fe1e319bd93af/accelerate-0.34.0-py3-none-any.whl (324 kB)                                                                                                                       
Collecting addict==2.4.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 2))                                       
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl (3.8 kB)                                                                                                                            
Collecting aiohappyeyeballs==2.4.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 3))                             
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/18/b6/58ea188899950d759a837f9a58b2aee1d1a380ea4d6211ce9b1823748851/aiohappyeyeballs-2.4.0-py3-none-any.whl (12 kB)                                                                                                                   
Collecting aiohttp==3.10.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 4))                                     
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8b/70/92ef8f2383577a8b2133ed674107c0e1d1586d15fc7d4f3f2a418bff41c7/aiohttp-3.10.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)                                                                                  
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 38.8 MB/s eta 0:00:00                                                                 
Collecting aiosignal==1.3.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 5))                                    
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)                                                                                                                         
Collecting aliyun-python-sdk-core==2.15.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 6))                      
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a7/43/f1a1876b04c45ba0b63852795102199c0356b1ddbed24dde7db7c89e1607/aliyun-python-sdk-core-2.15.2.tar.gz (449 kB)                                                                                                                     
  Preparing metadata (setup.py): started                                                                                                       
  Preparing metadata (setup.py): finished with status 'done'                                                                                   
Collecting aliyun-python-sdk-kms==2.16.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 7))                       
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/11/5c/0132193d7da2c735669a1ed103b142fd63c9455984d48c5a88a1a516efaa/aliyun_python_sdk_kms-2.16.5-py2.py3-none-any.whl (99 kB)                                                                                                         
Collecting annotated-types==0.7.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 8))                              
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/78/b6/6307fbef88d9b5ee7421e68d78a9f162e0da4900bc5f5793f6d3d0e34fb8/annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting anthropic==0.49.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 9))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/76/74/5d90ad14d55fbe3f9c474fdcb6e34b4bed99e3be8efac98734a5ddce88c1/anthropic-0.49.0-py3-none-any.whl (243 kB)
Collecting anyio==4.4.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 10))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7b/a2/10639a79341f6c019dedc95bd48a4928eed9f1d1197f4c04f546fc7ae0ff/anyio-4.4.0-py3-none-any.whl (86 kB)
Collecting async-timeout==4.0.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 11))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a7/fa/e01228c2938de91d47b307831c62ab9e4001e747789d0b05baf779a6488c/async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting attrs==24.2.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 12))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/21/5b6702a7f963e95456c0de2d495f67bf5fd62840ac655dc451586d23d39a/attrs-24.2.0-py3-none-any.whl (63 kB)
Collecting auto-gptq==0.7.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 13))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/16/72/de4c04fb0038681b64c2c6865b8c74ae4afdf2a7a73dab1f0ec7dc4c8214/auto_gptq-0.7.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.5/23.5 MB 122.5 MB/s eta 0:00:00
Collecting categories==0.3.7 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 14))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e6/8e/6b5ebc39663e22a8c7b77ab880b112252e9a14ce1cc221c1048a2d0069e1/categories-0.3.7-py3-none-any.whl (35 kB)
Collecting certifi==2025.7.14 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 15))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4f/52/34c6cf5bb9285074dc3531c437b3919e825d976fde097a7a73f79e726d03/certifi-2025.7.14-py3-none-any.whl (162 kB)
Collecting cffi==1.17.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 16))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bb/19/b51af9f4a4faa4a8ac5a0e5d5c2522dcd9703d07fac69da34a36c4d960d3/cffi-1.17.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (446 kB)
Collecting charset-normalizer==3.4.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 17))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2e/bb/d76d3d6e340fb0967c43c564101e28a78c9a363ea62f736a68af59ee3683/charset_normalizer-3.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
Collecting click==8.1.7 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 18))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl (97 kB)
Collecting cloudpickle==3.0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 19))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/96/43/dae06432d0c4b1dc9e9149ad37b4ca8384cf6eb7700cd9215b177b914f0a/cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting coloredlogs==15.0.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 20))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a7/06/3d6badcf13db419e25b07041d9c7b4a2c331d3f4e7134445ec5df57714cd/coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting contourpy==1.1.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 21))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8e/71/7f20855592cc929bc206810432b991ec4c702dc26b0567b132e52c85536f/contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
Collecting crcmod==1.7 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 22))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/b0/e595ce2a2527e169c3bcd6c33d2473c1918e0b7f6826a043ca1245dd4e5b/crcmod-1.7.tar.gz (89 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting cryptography==43.0.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 23))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ad/43/7a9920135b0d5437cc2f8f529fa757431eb6a7736ddfadfdee1cc5890800/cryptography-43.0.1-cp37-abi3-manylinux_2_28_x86_64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 161.5 MB/s eta 0:00:00
Collecting cycler==0.12.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 24))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting datasets==3.0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 25))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a5/52/45dab187f03d48c765b94db0464f5c10431756e47ae4cc6a8029a7d57a36/datasets-3.0.0-py3-none-any.whl (474 kB)
Collecting deepspeed==0.16.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 26))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d6/79/49cdf7d168b9ddcefeec6fda7a094a98bb48b046d56c7f4b2e092124534f/deepspeed-0.16.2.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 134.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting dill==0.3.8 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 27))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c9/7a/cef76fd8438a42f96db64ddaa85280485a9c395e7df3db8158cfec1eee34/dill-0.3.8-py3-none-any.whl (116 kB)
Collecting diskcache==5.6.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 28))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl (45 kB)
Collecting distro==1.9.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 29))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/12/b3/231ffd4ab1fc9d679809f356cebee130ac7daa00d6d6f3206dd4fd137e9e/distro-1.9.0-py3-none-any.whl (20 kB)
Collecting einops==0.8.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 30))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/5a/f0b9ad6c0a9017e62d4735daaeb11ba3b6c009d69a26141b258cd37b5588/einops-0.8.0-py3-none-any.whl (43 kB)
Collecting evaluate==0.4.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 31))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a2/e7/cbca9e2d2590eb9b5aa8f7ebabe1beb1498f9462d2ecede5c9fd9735faaf/evaluate-0.4.3-py3-none-any.whl (84 kB)
Collecting exceptiongroup==1.2.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 32))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/02/cc/b7e31358aac6ed1ef2bb790a9746ac2c69bcb3c8588b41616914eb106eaf/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Collecting fastapi==0.112.4 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 33))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f5/cf/5b703250f4d85e86ec13ec28bb5ac36790092bfe45e94e414529371d6f11/fastapi-0.112.4-py3-none-any.whl (93 kB)
Collecting filelock==3.16.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 34))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b9/f8/feced7779d755758a52d1f6635d990b8d98dc0a29fa568bbe0625f18fdf3/filelock-3.16.1-py3-none-any.whl (16 kB)
Collecting fonttools==4.53.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 35))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f1/d1/8a596e41e4df480e186de3cd0e90a461a01b7e4f20b5443a5c2a87567e18/fonttools-4.53.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 108.9 MB/s eta 0:00:00
Collecting frozenlist==1.4.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 36))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/45/4d/175b16d42daae8013bb1872f6d0870abd87da93e0a36706da4c9ba655d19/frozenlist-1.4.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (240 kB)
Collecting fschat==0.2.36 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 37))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/43/cd/3651634ab25f74e64eaf6a6e08e359320d6b26e637afe622762fe99d127b/fschat-0.2.36-py3-none-any.whl (256 kB)
Collecting fsspec==2025.3.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 38))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/56/53/eb690efa8513166adef3e0669afd31e95ffde69fb3c52ec2ac7223ed6018/fsspec-2025.3.0-py3-none-any.whl (193 kB)
Collecting fuzzywuzzy==0.18.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 39))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/43/ff/74f23998ad2f93b945c0309f825be92e04e0348e062026998b5eefef4c33/fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Collecting gekko==1.2.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 40))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/47/45/e48a94be1b31b0354aa453b0c2474d4ceb4b45653066d1d94085ae45605b/gekko-1.2.1-py3-none-any.whl (13.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 118.0 MB/s eta 0:00:00
Collecting gguf==0.10.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 41))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1b/e4/c5f9bd71840ae9afb7e2b7c285ba209f2ef5e9cd83885f8c596c551d3026/gguf-0.10.0-py3-none-any.whl (71 kB)
Collecting h11==0.14.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 42))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl (58 kB)
Collecting hf-xet==1.1.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 43))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6d/2f/6cad7b5fe86b7652579346cb7f85156c11761df26435651cbba89376cd2c/hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 154.9 MB/s eta 0:00:00
Collecting hjson==3.1.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 44))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1f/7f/13cd798d180af4bf4c0ceddeefba2b864a63c71645abc0308b768d67bb81/hjson-3.1.0-py3-none-any.whl (54 kB)
Collecting httpcore==1.0.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 45))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/78/d4/e5d7e4f2174f8a4d63c8897d79eb8fe2503f7ecc03282fee1fa2719c2704/httpcore-1.0.5-py3-none-any.whl (77 kB)
Collecting httptools==0.6.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 46))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c8/4d/1e14e818a086ce800a57c5025707ecbc66083921754b77f5e41879e132cd/httptools-0.6.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (354 kB)
Collecting httpx==0.27.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 47))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/41/7b/ddacf6dcebb42466abd03f368782142baa82e08fc0c1f8eaa05b4bae87d5/httpx-0.27.0-py3-none-any.whl (75 kB)
Collecting huggingface-hub==0.34.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 48))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8c/cf/dd53c0132f50f258b06dd37a4616817b1f1f6a6b38382c06effd04bb6881/huggingface_hub-0.34.1-py3-none-any.whl (558 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 558.8/558.8 kB 66.2 MB/s eta 0:00:00
Collecting humanfriendly==10.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 49))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f0/0f/310fb31e39e2d734ccaa2c0fb981ee41f7bd5056ce9bc29b2248bd569169/humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting idna==3.10 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 50))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl (70 kB)
Collecting imbalanced-learn==0.12.4 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 51))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d8/0d/c3bfccc5d460eec8ff56889802aa88f5d07280d5282b307a74558e6edc44/imbalanced_learn-0.12.4-py3-none-any.whl (258 kB)
Collecting imblearn==0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 52))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/81/a7/4179e6ebfd654bd0eac0b9c06125b8b4c96a9d0a8ff9e9507eb2a26d2d7e/imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Collecting importlib-metadata==8.5.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 53))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a0/d9/a1e041c5e7caa9a05c925f4bdbdfb7f006d1f74996af53467bc394c97be7/importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Collecting importlib-resources==6.4.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 54))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e1/6a/4604f9ae2fa62ef47b9de2fa5ad599589d28c9fd1d335f32759813dfa91e/importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Collecting interegular==0.3.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 55))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c4/01/72d6472f80651673716d1deda2a5bbb633e563ecf94f4479da5519d69d25/interegular-0.3.3-py37-none-any.whl (23 kB)
Collecting isal==1.7.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 56))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/14/42/f0441b2615694208270974e5b91f4dad5f96179832559174d4d8278f8767/isal-1.7.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (258 kB)
Collecting jieba==0.42.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 57))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz (19.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting jinja2==3.1.4 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 58))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/31/80/3a54838c3fb461f6fec263ebf3a3a41771bd05190238de3486aae8540c36/jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting jiter==0.5.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 59))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b5/2c/1d84255c3a49aa1fa5c5fb0b000c2efa06a210358c9fe1d8bb399e944ddb/jiter-0.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (319 kB)
Collecting jmespath==0.10.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 60))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting joblib==1.4.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 61))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/91/29/df4b9b42f2be0b623cbd5e2140cafcaa2bef0759a00b7b70104dcfe2fb51/joblib-1.4.2-py3-none-any.whl (301 kB)
Collecting jsonschema==4.23.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 62))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/4a/4f9dbeb84e8850557c02365a0eee0649abe5eb1d84af92a25731c6c0f922/jsonschema-4.23.0-py3-none-any.whl (88 kB)
Collecting jsonschema-specifications==2023.12.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 63))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ee/07/44bd408781594c4d0a027666ef27fab1e441b109dc3b76b4f836f8fd04fe/jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting kiwisolver==1.4.7 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 64))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/76/36/ae40d7a3171e06f55ac77fe5536079e7be1d8be2a8210e08975c7f9b4d54/kiwisolver-1.4.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 118.0 MB/s eta 0:00:00
Collecting lark==1.2.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 65))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2d/00/d90b10b962b4277f5e64a78b6609968859ff86889f5b898c1a778c06ec00/lark-1.2.2-py3-none-any.whl (111 kB)
Collecting lightning-utilities==0.11.9 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 66))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/85/f3/1305321a12c984405e26fc64b5d521569e9872fb811f4aace8e168099160/lightning_utilities-0.11.9-py3-none-any.whl (28 kB)
Collecting llmlingua==0.2.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 67))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6e/3e/221fe46a3338f2babdb2082ee42df88fcaa8ea0e639e832cbb1b93c5923a/llmlingua-0.2.2-py3-none-any.whl (30 kB)
Collecting llvmlite==0.41.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 68))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/46/a5/de824aba87a62e0da43f9b590ac91709d460a61e03f1b430b83ca64b76dc/llvmlite-0.41.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 MB 125.4 MB/s eta 0:00:00
Collecting lm-format-enforcer==0.10.6 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 69))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4f/6e/d140b5eb41541afebea1c27013bc19b5a1cafd0cd330d9aa3458833ee44a/lm_format_enforcer-0.10.6-py3-none-any.whl (43 kB)
Collecting markdown-it-py==3.0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 70))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting markdown2==2.5.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 71))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/30/2b/8653ae6d18e20183fc6051fd2e10cd0c46e16a6b71eb34edef8d465dc969/markdown2-2.5.1-py2.py3-none-any.whl (48 kB)
Collecting markupsafe==2.1.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 72))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c7/bd/50319665ce81bb10e90d1cf76f9e1aa269ea6f7fa30ab4521f14d122a3df/MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
Collecting matplotlib==3.7.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 73))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/30/33/cc27211d2ffeee4fd7402dca137b6e8a83f6dcae3d4be8d0ad5068555561/matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 26.5 MB/s eta 0:00:00
Collecting mdurl==0.1.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 74))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting mistral-common==1.4.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 75))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/df/ea/010bac65fffcea4f72ccedd4580d4a084fb75c17081e88d4fb69e2c5207d/mistral_common-1.4.3-py3-none-any.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 125.2 MB/s eta 0:00:00
Collecting modelscope==1.17.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 76))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3b/99/52014a331a516ee850e87c784a72269d23bcf56d8892984bcf01be3faee7/modelscope-1.17.1-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 110.9 MB/s eta 0:00:00
Collecting mpmath==1.3.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 77))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting msgpack==1.1.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 78))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/55/f6/d4859a158a915be52eecd52dee9761ab3a5d84c834a1d13ffc198e068a48/msgpack-1.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
Collecting msgspec==0.18.6 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 79))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/21/e0/1dff019ae22b7d47782d6f1180760828bc96fde368aea983d8e5d872833a/msgspec-0.18.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Collecting multidict==6.1.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 80))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2e/a9/83692e37d8152f104333132105b67100aabfb2e96a87f6bed67f566035a7/multidict-6.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)
Collecting multiprocess==0.70.16 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 81))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ea/89/38df130f2c799090c978b366cfdf5b96d08de5b29a4a293df7f7429fa50b/multiprocess-0.70.16-py38-none-any.whl (132 kB)
Collecting networkx==3.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 82))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a8/05/9d4f9b78ead6b2661d6e8ea772e111fc4a9fbd866ad0c81906c11206b55e/networkx-3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 116.0 MB/s eta 0:00:00
Collecting nh3==0.2.21 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 83))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/11/a9/1cd3c6964ec51daed7b01ca4686a5c793581bf4492cbd7274b3f544c9abe/nh3-0.2.21-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (739 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.0/739.0 kB 103.1 MB/s eta 0:00:00
Collecting ninja==1.11.1.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 84))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/35/a8e38d54768e67324e365e2a41162be298f51ec93e6bd4b18d237d7250d8/ninja-1.11.1.3-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (422 kB)
Collecting nltk==3.9.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 85))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4d/66/7d9e26593edda06e8cb531874633f7c2372279c3b0f46235539fe546df8b/nltk-3.9.1-py3-none-any.whl (1.5 MB)
Collecting numba==0.58.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 86))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6e/03/c658004b4b4d52dca7a74582e9fc3e20f94c17cb4b797eb3601876759540/numba-0.58.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 114.6 MB/s eta 0:00:00
Collecting numpy==1.24.4 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 87))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/98/5d/5738903efe0ecb73e51eb44feafba32bdba2081263d40c5043568ff60faf/numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 165.8 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.1.3.1 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 88))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/37/6d/121efd7382d5b0284239f4ab1fc1590d86d34ed4a4a2fdb13b30ca8e5740/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 35.3 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 89))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7e/00/6b218edd739ecfc60524e585ba8e6b00554dd908de2c9c66c1af3e44e18d/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 91.0 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 90))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b6/9f/c64c03f49d6fbc56196664d05dba14e3a561038a81a638eeb47f4d4cfd48/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 164.5 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 91))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/eb/d5/c68b1d2cdfcc59e72e8a5949a37ddb22ae6cade80cd4a57a84d4c8b55472/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 125.8 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 92))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9f/fd/713452cd72343f682b1c7b9321e23829f00b842ceaedcda96e742ea0b0b3/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 33.3 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.0.2.54 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 93))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/86/94/eb540db023ce1d162e7bea9f8f5aa781d57c65aed513c33ee9a5123ead4d/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 61.0 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.2.106 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 94))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/31/4890b1c9abc496303412947fc7dcea3d14861720642b49e8ceed89636705/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 33.2 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.4.5.107 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 95))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bc/1d/8de1e5c67099015c834315e333911273a8c6aaba78923dd1d1e25fc5f217/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 38.3 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.1.0.106 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 96))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/65/5b/cfaeebf25cd9fdec14338ccb16f6b2c4c7fa9163aefcf057d86b9cc248bb/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 41.7 MB/s eta 0:00:00
Collecting nvidia-ml-py==12.560.30 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 97))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b7/f3/a69ce0b1a1e12fbf6b2ad9f4c14c9999fdbdf15f2478d210f0fd501ddc98/nvidia_ml_py-12.560.30-py3-none-any.whl (40 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 98))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4b/2a/0a131f572aa09f741c30ccd45a8e56316e8be8dfc7bc19bf0ab7cfef7b19/nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 42.9 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12==12.6.20 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 99))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/59/65/7ff0569494fbaea45ad2814972cc88da843d53cc96eb8554fcd0908941d9/nvidia_nvjitlink_cu12-12.6.20-py3-none-manylinux2014_x86_64.whl (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 46.2 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.1.105 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 100))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/da/d3/8057f0587683ed2fcd4dbfbdfdfa807b9160b809976099d36b8f60d08f03/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Collecting openai==1.7.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 101))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2a/70/5ff7a2c5b37f6cab5ed3df59539d80d959e210d1127dea8e3de14897c4f3/openai-1.7.0-py3-none-any.whl (224 kB)
Collecting optimum==1.23.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 102))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/48/33/97cf226c47e4cf5a79159668732038cdd6c0199c72782d5b5a0db54f9a2d/optimum-1.23.3-py3-none-any.whl (424 kB)
Collecting oss2==2.19.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 103))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e2/ec/31baa9e9fa4a71aab9603e184db495b7cb4d1034af6bec0f11ba7cca034f/oss2-2.19.0.tar.gz (298 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting outlines==0.0.46 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 104))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fd/2c/1ce85b81b2f6835720db1fda9f2d4439a69458b119d2ad5fcf7cae573923/outlines-0.0.46-py3-none-any.whl (101 kB)
Requirement already satisfied: packaging==25.0 in /mnt/data5/dock/miniconda3/envs/DAC/lib/python3.8/site-packages (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 105)) (25.0)
Collecting pandas==2.0.3 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 106))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f8/7f/5b047effafbdd34e52c9e2d7e44f729a0655efafb22198c45cf692cdc157/pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 78.4 MB/s eta 0:00:00
Collecting partial-json-parser==0.2.1.1.post4 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 107))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9c/93/791cbea58b8dc27dc76621438d7b030741a4ad3bb5c222363dd01057175a/partial_json_parser-0.2.1.1.post4-py3-none-any.whl (9.9 kB)
Collecting peft==0.13.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 108))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/78/9d/5f95bfb298c8d3b4e3a107701f9a4e7774a0d4d1f8eb0c9d5420b80f7c9d/peft-0.13.2-py3-none-any.whl (320 kB)
Collecting pillow==10.4.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 109))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fb/ad/435fe29865f98a8fbdc64add8875a6e4f8c97749a93577a8919ec6f32c64/pillow-10.4.0-cp38-cp38-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 112.7 MB/s eta 0:00:00
Collecting pkgutil-resolve-name==1.3.10 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 110))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c9/5c/3d4882ba113fd55bdba9326c1e4c62a15e674a2501de4869e6bd6301f87e/pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting prometheus-client==0.21.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 111))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/84/2d/46ed6436849c2c88228c3111865f44311cff784b4aabcdef4ea2545dbc3d/prometheus_client-0.21.0-py3-none-any.whl (54 kB)
Collecting prometheus-fastapi-instrumentator==7.0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 112))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/59/66/2e93a8f56adb51ede41d0ef5f4f0277522acc4adc87937f5457b7b5692a8/prometheus_fastapi_instrumentator-7.0.0-py3-none-any.whl (19 kB)
Collecting protobuf==5.28.2 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 113))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/23/08/a1ce0415a115c2b703bfa798f06f0e43ca91dbe29d6180bf86a9287b15e2/protobuf-5.28.2-cp38-abi3-manylinux2014_x86_64.whl (316 kB)
Collecting psutil==6.0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 114))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/19/74/f59e7e0d392bc1070e9a70e2f9190d652487ac115bb16e2eff6b22ad1d24/psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (290 kB)
Collecting py-cpuinfo==9.0.0 (from -r /mnt/data5/dock/codes/DAC/condaenv.7hkxe2xs.requirements.txt (line 115))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e0/a9/023730ba63db1e494a271cb018dcd361bd2c917ba7004c3e49d5daf795a2/py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)

Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.9; 0.1.1 Requires-Python >=3.9; 0.1.10 Requires-Python >=3.9; 0.1.11 Requires-Python >=3.9; 0.1.12 Requires-Python >=3.9; 0.1.13 Requires-Python >=3.9; 0.1.14 Requires-Python >=3.9; 0.1.2 Requires-Python >=3.9; 0.1.3 Requires-Python >=3.9; 0.1.4 Requires-Python >=3.9; 0.1.5 Requires-Python >=3.9; 0.1.6 Requires-Python >=3.9; 0.1.7 Requires-Python >=3.9; 0.1.8 Requires-Python >=3.9; 0.1.9 Requires-Python >=3.9; 0.10.0 Requires-Python >=3.9; 0.12.0 Requires-Python >=3.9; 0.12.0.dev0 Requires-Python >=3.9; 0.13.0 Requires-Python >=3.10; 0.13.0 Requires-Python >=3.9; 0.13.1 Requires-Python >=3.9; 0.14.0 Requires-Python >=3.10; 0.14.0 Requires-Python >=3.9; 0.14.0 Requires-Python >=3.9.0; 0.14.1 Requires-Python >=3.9; 0.14.2 Requires-Python >=3.9; 0.14.3 Requires-Python >=3.9; 0.15.0 Requires-Python >=3.9; 0.15.0 Requires-Python >=3.9.0; 0.15.1 Requires-Python >=3.9; 0.15.1 Requires-Python >=3.9.0; 0.15.2 Requires-Python >=3.9; 0.15.2 Requires-Python >=3.9.0; 0.16.0 Requires-Python >=3.9.0; 0.17.0 Requires-Python >=3.9.0; 0.17.1 Requires-Python >=3.9.0; 0.19.0 Requires-Python >=3.9; 0.2.0 Requires-Python <3.13,>=3.9; 0.2.1 Requires-Python <3.13,>=3.9; 0.2.3 Requires-Python <3.13,>=3.9; 0.22.0 Requires-Python >=3.9; 0.22.1 Requires-Python >=3.9; 0.42.0 Requires-Python >=3.9; 0.42.0rc1 Requires-Python >=3.9; 0.43.0 Requires-Python >=3.9; 0.43.0rc1 Requires-Python >=3.9; 0.44.0 Requires-Python >=3.10; 0.44.0rc1 Requires-Python >=3.10; 0.44.0rc2 Requires-Python >=3.10; 0.59.0 Requires-Python >=3.9; 0.59.0rc1 Requires-Python >=3.9; 0.59.1 Requires-Python >=3.9; 0.60.0 Requires-Python >=3.9; 0.60.0rc1 Requires-Python >=3.9; 0.61.0 Requires-Python >=3.10; 0.61.0rc1 Requires-Python >=3.10; 0.61.0rc2 Requires-Python >=3.10; 0.61.1rc1 Requires-Python >=3.10; 0.61.2 Requires-Python >=3.10; 1.0.0 Requires-Python <3.13,>=3.9; 1.0.1 Requires-Python <3.13,>=3.9; 1.0.2 Requires-Python <3.13,>=3.9; 1.0.3 Requires-Python <3.13,>=3.9; 1.0.4 Requires-Python <3.13,>=3.9; 1.0.dev1 Requires-Python >=3.10; 1.0.dev2 Requires-Python >=3.10; 1.1.0 Requires-Python <3.13,>=3.9; 1.1.0 Requires-Python >=3.9.0; 1.1.1 Requires-Python <3.13,>=3.9; 1.1.1 Requires-Python >=3.9.0; 1.10.0 Requires-Python >=3.9.0; 1.2.0 Requires-Python <3.13,>=3.9; 1.2.0 Requires-Python >=3.9; 1.2.0 Requires-Python >=3.9.0; 1.2.1 Requires-Python <3.13,>=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9.0; 1.2.1rc1 Requires-Python >=3.9; 1.2.2 Requires-Python <3.13,>=3.9; 1.2.3 Requires-Python <3.13,>=3.9; 1.24.0 Requires-Python >=3.9.0; 1.25.0 Requires-Python >=3.9; 1.25.0 Requires-Python >=3.9.0; 1.25.1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9.0; 1.25.2 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9.0; 1.25.3 Requires-Python >=3.9.0; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0 Requires-Python >=3.9.0; 1.26.1 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python >=3.9.0; 1.26.2 Requires-Python >=3.9; 1.26.3 Requires-Python >=3.9; 1.26.4 Requires-Python >=3.9; 1.27.0 Requires-Python >=3.9.0; 1.3.0 Requires-Python >=3.9; 1.3.0 Requires-Python >=3.9.0; 1.3.1 Requires-Python >=3.10; 1.3.2 Requires-Python >=3.10; 1.3.2 Requires-Python >=3.9; 1.3.3 Requires-Python >=3.11; 1.4.0 Requires-Python >=3.9; 1.4.0 Requires-Python >=3.9.0; 1.4.0a4 Requires-Python >=3.9; 1.4.0a5 Requires-Python >=3.9; 1.4.0a6 Requires-Python >=3.9; 1.4.0a7 Requires-Python >=3.9; 1.4.10rc0 Requires-Python >=3.10; 1.4.8 Requires-Python >=3.10; 1.4.9 Requires-Python >=3.10; 1.5.0 Requires-Python >=3.9; 1.5.0 Requires-Python >=3.9.0; 1.5.1 Requires-Python >=3.9; 1.5.1 Requires-Python >=3.9.0; 1.5.2 Requires-Python >=3.9.0; 1.6.0 Requires-Python <3.14,>=3.9.0; 1.6.0 Requires-Python >=3.9; 1.6.0 Requires-Python >=3.9.0; 1.6.1 Requires-Python <3.14,>=3.9.0; 1.6.2 Requires-Python <3.14,>=3.9.0; 1.6.2 Requires-Python >=3.9; 1.6.3 Requires-Python <3.14,>=3.9.0; 1.6.4 Requires-Python <3.14,>=3.9.0; 1.7.0 Requires-Python <3.14,>=3.9.0; 1.7.0 Requires-Python >=3.9; 1.7.0 Requires-Python >=3.9.0; 1.8.0 Requires-Python <3.14,>=3.9.0; 1.8.0 Requires-Python >=3.9.0; 1.8.1 Requires-Python <3.14,>=3.9.0; 1.8.1 Requires-Python >=3.9.0; 1.8.2 Requires-Python <3.14,>=3.9.0; 1.8.3 Requires-Python <3.14,>=3.9.0; 1.8.4 Requires-Python <3.14,>=3.9.0; 1.9.0 Requires-Python >=3.9.0; 11.0.0 Requires-Python >=3.9; 11.1.0 Requires-Python >=3.9; 11.2.1 Requires-Python >=3.9; 11.3.0 Requires-Python >=3.9; 2.0.0 Requires-Python >=3.9; 2.0.0b1 Requires-Python >=3.9; 2.0.1 Requires-Python >=3.9; 2.0.2 Requires-Python >=3.9; 2.1.0 Requires-Python >=3.10; 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 2.1.1 Requires-Python >=3.10; 2.1.1 Requires-Python >=3.9; 2.1.2 Requires-Python >=3.10; 2.1.2 Requires-Python >=3.9; 2.1.3 Requires-Python >=3.10; 2.1.3 Requires-Python >=3.9; 2.1.4 Requires-Python >=3.9; 2.10.1 Requires-Python <3; 2.11.0 Requires-Python <3; 2.11.1 Requires-Python <3; 2.2.0 Requires-Python >=3.10; 2.2.0 Requires-Python >=3.9; 2.2.0rc0 Requires-Python >=3.9; 2.2.1 Requires-Python >=3.10; 2.2.1 Requires-Python >=3.9; 2.2.2 Requires-Python >=3.10; 2.2.2 Requires-Python >=3.9; 2.2.3 Requires-Python >=3.10; 2.2.3 Requires-Python >=3.9; 2.2.4 Requires-Python >=3.10; 2.2.5 Requires-Python >=3.10; 2.2.6 Requires-Python >=3.10; 2.3.0 Requires-Python >=3.11; 2.3.0 Requires-Python >=3.9; 2.3.1 Requires-Python >=3.11; 2.3.1 Requires-Python >=3.9; 2.3.2 Requires-Python >=3.11; 2.3.2 Requires-Python >=3.9; 2.4.0 Requires-Python <3; 2.4.1 Requires-Python <3; 2.4.2 Requires-Python <3; 2.4.3 Requires-Python <3; 2.4.4 Requires-Python <3; 2.4.5 Requires-Python >=3.9; 2.4.6 Requires-Python >=3.9; 2.4.7 Requires-Python >=3.9; 2.4.8 Requires-Python >=3.9; 2.5.0 Requires-Python <3; 2.5.0 Requires-Python >=3.9; 2.5.1 Requires-Python <3; 2.5.2 Requires-Python <3; 2.5.2 Requires-Python <4,>=3.9; 2.5.3 Requires-Python <4,>=3.9; 2.5.4 Requires-Python <4,>=3.9; 2.6.0 Requires-Python <3; 2.6.0 Requires-Python >=3.9; 2.6.1 Requires-Python <3; 2.6.1 Requires-Python >=3.9; 2.6.2 Requires-Python <3; 2.7.0 Requires-Python <3; 2.7.2 Requires-Python <3; 2.8.0 Requires-Python <3; 2.8.1 Requires-Python <3; 2.8.2 Requires-Python <3; 2.8.3 Requires-Python <3; 2.8.4 Requires-Python <3; 2.8.5 Requires-Python <3; 2.8.6 Requires-Python <3; 2.8.7 Requires-Python <3; 2.9.2 Requires-Python <3; 2024.10.1 Requires-Python >=3.9; 2025.3.2 Requires-Python >=3.9; 2025.4.1 Requires-Python >=3.9; 2025.5.0 Requires-Python >=3.9; 2025.5.1 Requires-Python >=3.9; 2025.7.0 Requires-Python >=3.9; 3.0.0 Requires-Python >=3.9; 3.0.1 Requires-Python >=3.9; 3.0.2 Requires-Python >=3.9; 3.10.0 Requires-Python >=3.10; 3.10.0rc1 Requires-Python >=3.10; 3.10.1 Requires-Python >=3.10; 3.10.3 Requires-Python >=3.10; 3.10.5 Requires-Python >=3.10; 3.11.0 Requires-Python >=3.9; 3.11.0b0 Requires-Python >=3.9; 3.11.0b1 Requires-Python >=3.9; 3.11.0b2 Requires-Python >=3.9; 3.11.0b3 Requires-Python >=3.9; 3.11.0b4 Requires-Python >=3.9; 3.11.0b5 Requires-Python >=3.9; 3.11.0rc0 Requires-Python >=3.9; 3.11.0rc1 Requires-Python >=3.9; 3.11.0rc2 Requires-Python >=3.9; 3.11.1 Requires-Python >=3.9; 3.11.10 Requires-Python >=3.9; 3.11.11 Requires-Python >=3.9; 3.11.12 Requires-Python >=3.9; 3.11.13 Requires-Python >=3.9; 3.11.14 Requires-Python >=3.9; 3.11.15 Requires-Python >=3.9; 3.11.16 Requires-Python >=3.9; 3.11.17 Requires-Python >=3.9; 3.11.18 Requires-Python >=3.9; 3.11.2 Requires-Python >=3.9; 3.11.3 Requires-Python >=3.9; 3.11.4 Requires-Python >=3.9; 3.11.5 Requires-Python >=3.9; 3.11.6 Requires-Python >=3.9; 3.11.7 Requires-Python >=3.9; 3.11.8 Requires-Python >=3.9; 3.11.9 Requires-Python >=3.9; 3.12.0 Requires-Python >=3.9; 3.12.0b0 Requires-Python >=3.9; 3.12.0b1 Requires-Python >=3.9; 3.12.0b2 Requires-Python >=3.9; 3.12.0b3 Requires-Python >=3.9; 3.12.0rc0 Requires-Python >=3.9; 3.12.0rc1 Requires-Python >=3.9; 3.12.1 Requires-Python >=3.9; 3.12.10 Requires-Python >=3.9; 3.12.11 Requires-Python >=3.9; 3.12.12 Requires-Python >=3.9; 3.12.13 Requires-Python >=3.9; 3.12.14 Requires-Python >=3.9; 3.12.15 Requires-Python >=3.9; 3.12.1rc0 Requires-Python >=3.9; 3.12.2 Requires-Python >=3.9; 3.12.3 Requires-Python >=3.9; 3.12.4 Requires-Python >=3.9; 3.12.6 Requires-Python >=3.9; 3.12.7 Requires-Python >=3.9; 3.12.7rc0 Requires-Python >=3.9; 3.12.8 Requires-Python >=3.9; 3.12.9 Requires-Python >=3.9; 3.17.0 Requires-Python >=3.9; 3.18.0 Requires-Python >=3.9; 3.19.1 Requires-Python >=3.9; 3.2 Requires-Python >=3.9; 3.2.0 Requires-Python >=3.9.0; 3.2.1 Requires-Python >=3.9; 3.2rc0 Requires-Python >=3.9; 3.3 Requires-Python >=3.10; 3.3.0 Requires-Python >=3.9.0; 3.3.1 Requires-Python >=3.9.0; 3.3.2 Requires-Python >=3.9.0; 3.3rc0 Requires-Python >=3.10; 3.4 Requires-Python >=3.10; 3.4.0 Requires-Python >=3.9.0; 3.4.1 Requires-Python >=3.10; 3.4.1 Requires-Python >=3.9.0; 3.4.2 Requires-Python >=3.10; 3.4rc0 Requires-Python >=3.10; 3.5 Requires-Python >=3.11; 3.5.0 Requires-Python >=3.9.0; 3.5.1 Requires-Python >=3.9.0; 3.5rc0 Requires-Python >=3.11; 3.6.0 Requires-Python >=3.9.0; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9; 3.8.1 Requires-Python >=3.9; 3.8.2 Requires-Python >=3.9; 3.8.3 Requires-Python >=3.9; 3.8.4 Requires-Python >=3.9; 3.9.0 Requires-Python >=3.9; 3.9.0rc2 Requires-Python >=3.9; 3.9.1 Requires-Python >=3.9; 3.9.1.post1 Requires-Python >=3.9; 3.9.2 Requires-Python >=3.9; 3.9.3 Requires-Python >=3.9; 3.9.4 Requires-Python >=3.9; 4.0.0 Requires-Python >=3.10; 4.0.0 Requires-Python >=3.9.0; 4.10.0 Requires-Python >=3.9; 4.24.0 Requires-Python >=3.9; 4.24.1 Requires-Python >=3.9; 4.25.0 Requires-Python >=3.9; 4.25.1 Requires-Python >=3.9; 4.58.0 Requires-Python >=3.9; 4.58.1 Requires-Python >=3.9; 4.58.2 Requires-Python >=3.9; 4.58.3 Requires-Python >=3.9; 4.58.4 Requires-Python >=3.9; 4.58.5 Requires-Python >=3.9; 4.59.0 Requires-Python >=3.9; 4.59.1 Requires-Python >=3.9; 4.6.0 Requires-Python >=3.9; 4.6.1 Requires-Python >=3.9; 4.6.2.post1 Requires-Python >=3.9; 4.7.0 Requires-Python >=3.9; 4.8.0 Requires-Python >=3.9; 4.9.0 Requires-Python >=3.9; 6.2.0 Requires-Python >=3.9; 6.3.0 Requires-Python >=3.9; 6.3.1 Requires-Python >=3.9; 6.3.2 Requires-Python >=3.9; 6.30.0 Requires-Python >=3.9; 6.30.0rc1 Requires-Python >=3.9; 6.30.0rc2 Requires-Python >=3.9; 6.30.1 Requires-Python >=3.9; 6.30.2 Requires-Python >=3.9; 6.31.0 Requires-Python >=3.9; 6.31.0rc1 Requires-Python >=3.9; 6.31.0rc2 Requires-Python >=3.9; 6.31.1 Requires-Python >=3.9; 6.32.0 Requires-Python >=3.9; 6.32.0rc1 Requires-Python >=3.9; 6.32.0rc2 Requires-Python >=3.9; 6.4.0 Requires-Python >=3.9; 6.4.1 Requires-Python >=3.9; 6.4.2 Requires-Python >=3.9; 6.4.3 Requires-Python >=3.9; 6.4.4 Requires-Python >=3.9; 6.5.0 Requires-Python >=3.9; 6.5.1 Requires-Python >=3.9; 6.5.2 Requires-Python >=3.9; 6.6.0 Requires-Python >=3.9; 6.6.1 Requires-Python >=3.9; 6.6.2 Requires-Python >=3.9; 6.6.3 Requires-Python >=3.9; 6.6.4 Requires-Python >=3.9; 8.2.0 Requires-Python >=3.10; 8.2.1 Requires-Python >=3.10; 8.2.2 Requires-Python >=3.10; 8.6.0 Requires-Python >=3.9; 8.6.1 Requires-Python >=3.9; 8.7.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement pyairports==2.1.1 (from versions: none)
ERROR: No matching distribution found for pyairports==2.1.1

failed

CondaEnvException: Pip failed

```

**Comment by frankjoey2048** [comment]
update: problem solved by following step -----
```
conda create -n dac python=3.10
pip install -r requiremenets.txt
```
and `requirements.txt` is ----
```
torch>=2.0.0
transformers>=4.30.0
accelerate>=0.20.0

# Required by transformers
huggingface-hub>=0.16.0
tokenizers>=0.13.0
safetensors>=0.3.0

# Basic utilities
numpy>=1.21.0
tqdm>=4.65.0
regex>=2022.0.0
filelock>=3.0.0
typing-extensions>=4.0.0
```

**Comment by QQQ-yi** [comment]
Hi @frankjoey2048, thank you so much for sharing your solution!

We're glad you were able to resolve the pip failed issue, and appreciate you taking the time to document the fix.

Based on your feedback, we've updated the setup instructions in the latest commit to make the installation process smoother for future users.

Thanks again for your contribution.
